import { EXPORT_CSS } from './manuscript'
import type { Usage } from './openai'

export interface ReviewMsg {
  role: 'user' | 'assistant'
  content: string
  sources?: string[]
  usage?: Usage
}

export interface SavedSession {
  id: string
  title: string
  ts: number
  model: string
  messages: ReviewMsg[]
}

const KEY = 'williamslab.review.sessions'

export function listSessions(): SavedSession[] {
  try {
    const raw = localStorage.getItem(KEY)
    const arr = raw ? (JSON.parse(raw) as SavedSession[]) : []
    return arr.sort((a, b) => b.ts - a.ts)
  } catch {
    return []
  }
}

function write(list: SavedSession[]) {
  try {
    localStorage.setItem(KEY, JSON.stringify(list))
  } catch {
    /* ignore quota */
  }
}

export function saveSession(s: SavedSession): void {
  const list = listSessions().filter((x) => x.id !== s.id)
  list.unshift(s)
  write(list.slice(0, 40))
}

export function removeSession(id: string): void {
  write(listSessions().filter((x) => x.id !== id))
}

export function sessionTitle(messages: ReviewMsg[]): string {
  const first = messages.find((m) => m.role === 'user')?.content ?? 'Knowledge review'
  return first.length > 60 ? first.slice(0, 57) + '…' : first
}

function dateStr(ts: number): string {
  const d = new Date(ts)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

// Full transcript as Markdown.
export function transcriptMarkdown(messages: ReviewMsg[], meta: { project: string; model: string; ts: number }): string {
  const lines: string[] = [
    `# Knowledge Review — ${meta.project}`,
    ``,
    `_${dateStr(meta.ts)} · model ${meta.model} · WilliamsLab_`,
    ``,
  ]
  messages.forEach((m) => {
    if (m.role === 'user') {
      lines.push(`## Q · ${m.content}`, ``)
    } else {
      lines.push(m.content.trim(), ``)
      if (m.sources?.length) lines.push(`_Grounded in: ${m.sources.join(', ')}_`, ``)
    }
  })
  return lines.join('\n')
}

// A one-page briefing: the questions asked + the key answers, styled for print.
export function onePagerHtml(messages: ReviewMsg[], meta: { project: string; question: string; model: string; ts: number }): string {
  const qa = []
  for (let i = 0; i < messages.length; i++) {
    if (messages[i].role === 'user') {
      const a = messages[i + 1]?.role === 'assistant' ? messages[i + 1] : undefined
      qa.push({ q: messages[i].content, a })
    }
  }
  const esc = (t: string) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  // minimal markdown → html for the answer bodies
  const mdInline = (t: string) =>
    esc(t)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
  const mdBlock = (t: string) =>
    t
      .split(/\n{2,}/)
      .map((para) => {
        const l = para.trim()
        if (/^#{1,3}\s/.test(l)) return `<h3>${mdInline(l.replace(/^#{1,3}\s/, ''))}</h3>`
        if (/^([-*])\s/m.test(l)) {
          const items = l.split(/\n/).filter((x) => /^([-*])\s/.test(x.trim())).map((x) => `<li>${mdInline(x.trim().replace(/^([-*])\s/, ''))}</li>`).join('')
          return `<ul>${items}</ul>`
        }
        return `<p>${mdInline(l)}</p>`
      })
      .join('\n')
  const body = qa
    .map(
      (item) => `<section class="qa">
    <h2>${esc(item.q)}</h2>
    ${item.a ? mdBlock(item.a.content) : '<p><em>(no answer)</em></p>'}
    ${item.a?.sources?.length ? `<p class="src">Grounded in: ${item.a.sources.map(esc).join(', ')}</p>` : ''}
  </section>`,
    )
    .join('\n')
  return `<!doctype html><html><head><meta charset="utf-8"><title>Knowledge Review OnePager — ${esc(meta.project)}</title><style>${EXPORT_CSS}
    .qa{margin:0 0 18px} .qa h2{font-size:15px;color:#0a1f6b;margin:0 0 6px;border-left:3px solid #e2001a;padding-left:9px}
    .src{font-size:11px;color:#667;font-style:italic;margin-top:6px}
  </style></head><body>
  <header><h1>Knowledge Review — OnePager</h1><p class="meta">${esc(meta.project)} · ${dateStr(meta.ts)} · model ${esc(meta.model)}</p></header>
  ${body}
  <footer>Generated by WilliamsLab · educational review, verify against primary sources.</footer>
  </body></html>`
}

export function download(name: string, mime: string, content: string): void {
  const url = URL.createObjectURL(new Blob([content], { type: mime }))
  const a = document.createElement('a')
  a.href = url
  a.download = name
  a.click()
  URL.revokeObjectURL(url)
}
